config/routes.rb
Rails.application.routes.draw do
  
  # Administrator namespace, password protected section of website.
  namespace :admin do 
    # Namespace root
    root 'pages#dashboard'

    # Login/Logout Routes
    get "login"  => "sessions#new",     :as => :login
    post "login" => "sessions#create",  :as => :sign_in
    get "logout" => "sessions#destroy", :as => :logout

    # Resources
    resources :posts do
      resources :comments
    end

    resources :projects do
      resources :comments
    end

    resources :tags
    
  end

  # Public part of the website
  root 'posts#index'
  
  resources :posts do 
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :tags

end

app/models/project.rb
class Project < ActiveRecord::Base

  # Associations
  belongs_to :administrator
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  # Scopes
  scope :recently_created, -> { order("created_at DESC") }
  scope :recently_updated, -> { order("updated_at DESC") }

  # Pagination
  self.per_page = 30
  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :find_project, :only => [:show, :edit, :update, :destroy]

  def index
    @projects = Project.recently_created.paginate(:page => params[:page])
  end

  def show

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.administrator_id = current_admin.id
    params[:project][:tag_ids].each do |tag_id|
      @project.tags << Tag.find(tag_id.to_i) unless tag_id == ""
    end
    if @project.save
      redirect_to([:admin, :projects], :notice => I18n.t("admin.projects.create.success"))
    else
      flash.now[:error] = I18n.t("admin.projects.create.error")
      render(:new)
    end
  end

  def edit

  end

  def update
    params[:project][:tag_ids].each do |tag_id|
      @project.tags << Tag.find(tag_id.to_i) unless tag_id == ""
    end
    if @project.update_attributes(project_params)
      redirect_to([:admin, :projects], :notice => I18n.t("admin.projects.create.success"))
    else
      flash.now[:error] = I18n.t("admin.projects.create.error")
      render(:edit)
    end
  end

  def destroy
    @project.destroy
    redirect_to([:admin, :projects], :notice => I18n.t("admin.projects.destroy.success"))
  end

private

  # Find post by ID
  def find_project
    @project = Project.find(params[:id])
  end

  # Set parameter permissions for post
  def project_params
    params.require(:project).permit(:title, :slug, :lead, :body, :administrator_id, :published, :published_on, :tag_ids)
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.published.recently_created
  end

  def show
    @project = Project.find(params[:id])
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/edit.html.haml
.row-fluid
  .col-md-2
    %ul.nav.nav-pills.nav-stacked
      %p.text-uppercase= "Weblog / edit project"
      = sub_menu_item(:projects, [:admin, :projects], menu_active?(:projects), "th-list")
      = sub_menu_item(:new_project, [:new, :admin, :project], menu_active?(:projects), "plus")
  .col-md-10
    = form_for(@project, :url => admin_project_path) do |f|
      .form-group
        = f.text_field :title, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.title")
      .form-group
        = f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {}, :multiple => true, :class => "form-control bootstrap-multiselect"
      .form-group
        = f.text_area :lead, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.lead")
      .form-group
        = f.text_area :body, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.body")
      .form-group
        = f.submit :submit, :class => "btn btn-primary"

app/views/admin/projects/index.html.haml
.col-md-2
  %ul.nav.nav-pills.nav-stacked
    %p.text-uppercase= "Weblog / projects"
    = sub_menu_item(:new_project, [:new, :admin, :project], menu_active?(:projects), "plus")
.col-md-10
  %table.table.table-striped
    %thead
      %tr
        %th= t("admin.projects.table.title")
        %th= t("admin.projects.table.lead")
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.title
          %td= project.lead

app/views/admin/projects/new.html.haml
.row-fluid
  .col-md-2
    %ul.nav.nav-pills.nav-stacked
      %p.text-uppercase= "Weblog / new project"
      = sub_menu_item(:projects, [:admin, :projects], menu_active?(:projects), "th-list")
  .col-md-10
    = form_for(@project, :url => admin_projects_path) do |f|
      .form-group
        = f.text_field :title, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.title")
      .form-group
        = f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {}, :multiple => true, :class => "form-control bootstrap-multiselect"
      .form-group
        = f.text_area :lead, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.lead")
      .form-group
        = f.text_area :body, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.body")
      .form-group
        = f.submit :submit, :class => "btn btn-primary"