config/routes.rb
Rails.application.routes.draw do
  
  # Administrator namespace, password protected section of website.
  namespace :admin do 
    # Namespace root
    root 'pages#dashboard'

    # Login/Logout Routes
    get "login"  => "sessions#new",     :as => :login
    post "login" => "sessions#create",  :as => :sign_in
    get "logout" => "sessions#destroy", :as => :logout

    # Resources
    resources :posts do
      resources :comments
    end

    resources :projects do
      resources :comments
    end

    resources :tags
    
  end

  # Public part of the website
  root 'posts#index'
  
  resources :posts do 
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resources :tags

end

app/models/post.rb
class Post < ActiveRecord::Base

  # Associations
  belongs_to :administrator
  has_many :taggings, :as => :taggable, :dependent => :destroy
  has_many :tags, :through => :taggings
  has_many :comments, :as => :commentable, :dependent => :destroy

  # Scopes
  scope :current_author, ->(author_id) { where(:administrator_id => author_id)}
  scope :published, -> { where("published = true") }
  scope :recently_created, -> { order("created_at DESC") }
  scope :recently_updated, -> { order("updated_at DESC") }

  # Pagination
  self.per_page = 30

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :find_post, :only => [:show, :edit, :update, :destroy]

  def index
    @posts = Post.current_author(current_admin.id).recently_created.paginate(:page => params[:page])
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.administrator_id = current_admin.id
    if params[:post][:slug].blank?
      @post.slug = @post.title
    end
    @post.slug = @post.slug.downcase.gsub!(" ", "-")
    params[:post][:tag_ids].each do |tag_id|
      @post.tags << Tag.find(tag_id.to_i) unless tag_id == ""
    end
    if @post.save
      redirect_to([:admin, :posts], :notice => I18n.t("admin.posts.create.success"))
    else
      flash.now[:error] = I18n.t("admin.posts.create.error")
      render(:new)
    end
  end

  def edit

  end

  def update
    if params[:post][:tag_ids]
      params[:post][:tag_ids].each do |tag_id|
        @post.tags << Tag.find(tag_id.to_i) unless tag_id == ""
      end
    end
    if @post.update_attributes(post_params)
      redirect_to([:admin, :posts], :notice => I18n.t("admin.posts.create.success"))
    else
      flash.now[:error] = I18n.t("admin.posts.create.error")
      render(:edit)
    end
  end

  def destroy
    @post.destroy
    redirect_to([:admin, :posts], :notice => I18n.t("admin.posts.destroy.success"))
  end

private

  # Find post by ID
  def find_post
    @post = Post.find(params[:id])
  end

  # Set parameter permissions for post
  def post_params
    params.require(:post).permit(:title, :slug, :lead, :body, :administrator_id, :published, :published_on, :tag_ids)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.published.recently_created
  end

  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/edit.html.haml
.row-fluid
  .col-md-2
    %ul.nav.nav-pills.nav-stacked
      %p.text-uppercase= "Weblog / edit post"
      = sub_menu_item(:posts, [:admin, :posts], menu_active?(:posts), "th-list")
      = sub_menu_item(:new_post, [:new, :admin, :post], menu_active?(:posts), "plus")
  .col-md-10
    = form_for(@post, :url => admin_post_path) do |f|
      .form-group
        = f.text_field :title, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.title")
      .form-group
        = f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {}, :multiple => true, :class => "form-control bootstrap-multiselect"
      .form-group
        = f.text_area :lead, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.lead"), :rows => "5"
      .form-group
        = f.text_area :body, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.body"), :rows => "15"
      .form-group
        = f.submit :submit, :class => "btn btn-primary"

app/views/admin/posts/index.html.haml
.col-md-2
  %ul.nav.nav-pills.nav-stacked
    %p.text-uppercase= "Weblog / posts"
    = sub_menu_item(:new_post, [:new, :admin, :post], menu_active?(:posts), "plus")
.col-md-10
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th.buttons
        %th= t("admin.table.title")
        %th= t("admin.table.slug")
        %th.extra-small
          %span.glyphicon.glyphicon-cloud-upload
        %th.text-right.datestamp= t("admin.table.published_on")
    %tbody
      - @posts.each do |post|
        %tr
          %td.buttons
            = link_to [:edit, :admin, post], :class => "btn btn-warning", :data => { :no_turbolink => true } do
              %span.glyphicon.glyphicon-pencil
            = link_to [:admin, post], :class => "btn btn-danger", :method => :delete, :data => { :confirm => t("admin.table.delete_confirm") } do
              %span.glyphicon.glyphicon-trash
          %td= post.title
          %td= post.slug
          %td
            = form_for(post, :url => admin_post_path(post), :method => :put, :class => "form-inline") do |f|
              = f.hidden_field :published_on, :value => DateTime.now
              = f.check_box :published, :class => "ajax-checkbox"
          %td.text-right
            - if post.published == true
              = post.published_on.strftime("%e %B %Y at %H:%M")
            - else
              .text-muted= t("admin.table.not_published")

app/views/admin/posts/new.html.haml
.row-fluid
  .col-md-2
    %ul.nav.nav-pills.nav-stacked
      %p.text-uppercase= "Weblog / new post"
      = sub_menu_item(:posts, [:admin, :posts], menu_active?(:posts), "th-list")
  .col-md-10
    = form_for(@post, :url => admin_posts_path) do |f|
      .form-group
        = f.text_field :title, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.title")
      .form-group
        = f.text_field :slug, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.slug")
      .form-group
        = f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {}, :multiple => true, :class => "form-control bootstrap-multiselect"
      .form-group
        = f.text_area :lead, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.lead"), :rows => "5"
      .form-group
        = f.text_area :body, :label => false, :class => "form-control", :placeholder => t("admin.placeholders.body"), :rows => "15"
      .form-group
        = f.submit :submit, :class => "btn btn-primary"